program Servisoft;

uses
  Forms,
  UPessoa in 'uPessoa.pas' {fPessoa},
  UDm1 in 'UDm1.pas' {Dm1: TDataModule},
  UDmCons in 'UDmCons.pas' {DmCons: TDataModule},
  UMenu in 'UMenu.pas' {fMenu},
  UPais in 'UPais.pas' {fPais},
  UGrupo in 'UGrupo.pas' {fGrupo},
  USitTributaria in 'USitTributaria.pas' {fSitTributaria},
  UClasFiscal in 'UClasFiscal.pas' {fClasFiscal},
  UNatOperacao in 'UNatOperacao.pas' {fNatOperacao},
  UProduto in 'UProduto.pas' {fProduto},
  UCondPgto in 'UCondPgto.pas' {fCondPgto},
  UTipoCobranca in 'UTipoCobranca.pas' {fTipoCobranca},
  UUF in 'UUF.pas' {fUF},
  UEmpresa in 'UEmpresa.pas' {fEmpresa},
  UBanco in 'UBanco.pas' {fBanco},
  UCondPgtoIt in 'UCondPgtoIt.pas' {fCondPgtoIt},
  UProdutoIt in 'UProdutoIt.pas' {fProdutoIt},
  UParametros in 'UParametros.pas' {fParametros},
  UContasPagar in 'UContasPagar.pas' {fContasPagar},
  UPrevCheques in 'UPrevCheques.pas' {fPrevCheques},
  UMovFinanceiro in 'UMovFinanceiro.pas' {fMovFinanceiro},
  UMovFinanceiroIt in 'UMovFinanceiroIt.pas' {fMovFinanceiroIt},
  UContasReceber in 'UContasReceber.pas' {fContasReceber},
  UDevolucaoRec in 'UDevolucaoRec.pas' {fDevolucaoRec},
  UDevolucaoPag in 'UDevolucaoPag.pas' {fDevolucaoPag},
  uSobre in 'uSobre.pas' {fSobre},
  uPortaImpressao in 'uPortaImpressao.pas' {fPortaImpressao},
  UPessoaRel in 'UPessoaRel.pas' {fPessoaRel},
  UMovFinanceiroRel in 'UMovFinanceiroRel.pas' {fMovFinanceiroRel},
  UPedidoRel in 'UPedidoRel.pas' {fPedidoRel},
  UContasReceberRel in 'UContasReceberRel.pas' {fContasReceberRel},
  UContasReceberDet in 'UContasReceberDet.pas' {fContasReceberDet},
  UContasReceberPgto in 'UContasReceberPgto.pas' {fContasReceberPgto},
  UJuros in 'UJuros.pas' {fJuros},
  UFluxoFuturo in 'UFluxoFuturo.pas' {fFluxoFuturo},
  uLogin in 'uLogin.pas' {fLogin},
  UUsuario in 'UUsuario.pas' {fUsuario},
  UContasPagarRel in 'UContasPagarRel.pas' {fContasPagarRel},
  UContasPagarDet in 'UContasPagarDet.pas' {fContasPagarDet},
  USenha in 'USenha.pas' {fSenha},
  UAutorizacao in 'UAutorizacao.pas' {fAutorizacao},
  UConsComissaoVend in 'UConsComissaoVend.pas' {fConsComissaoVend},
  UOrcamentoPrev in 'UOrcamentoPrev.pas' {fOrcamentoPrev},
  UOrcamentoPrevRel in 'UOrcamentoPrevRel.pas' {fOrcamentoPrevRel},
  UComissaoRel in 'UComissaoRel.pas' {fComissaoRel},
  UPedidoPrev in 'UPedidoPrev.pas' {fPedidoPrev},
  UPedidoPrevRel in 'UPedidoPrevRel.pas' {fPedidoPrevRel},
  UContasReceberCliente in 'UContasReceberCliente.pas' {fContasReceberCliente},
  UContasReceberClienteRel in 'UContasReceberClienteRel.pas' {fContasReceberClienteRel},
  uServico in 'uServico.pas' {fServico},
  uServicoC in 'uServicoC.pas' {fServicoC},
  uFormaPgtoC in 'uFormaPgtoC.pas' {fFormaPgtoC},
  uFormaPgto in 'uFormaPgto.pas' {fFormaPgto},
  uPessoac in 'uPessoac.pas' {fPessoaC},
  uCidadeC in 'uCidadeC.pas' {fCidadeC},
  uCidade in 'uCidade.pas' {fCidade},
  uTelefone in 'uTelefone.pas' {fTelefone},
  uPessoaServico in 'uPessoaServico.pas' {fPessoaServico},
  uOrcamentoInstC in 'uOrcamentoInstC.pas' {fOrcamentoInstC},
  uOrcamentoInst in 'uOrcamentoInst.pas' {fOrcamentoInst},
  uOrcamentoProd in 'uOrcamentoProd.pas' {fOrcamentoProd},
  uClausulaC in 'uClausulaC.pas' {fClausulaC},
  uClausula in 'uClausula.pas' {fClausula},
  uOrcamentoClausula in 'uOrcamentoClausula.pas' {fOrcamentoClausula},
  UMovAvulsoIt in 'UMovAvulsoIt.pas' {fMovAvulsoIt},
  UMovAvulso in 'UMovAvulso.pas' {fMovAvulso},
  UGeraMovMensal in 'UGeraMovMensal.pas' {fGeraMovMensal},
  UContasPagarPgto in 'UContasPagarPgto.pas' {fContasPagarPgto},
  uCentroCustoC in 'uCentroCustoC.pas' {fCentroCustoC},
  uCentroCusto in 'uCentroCusto.pas' {fCentroCusto},
  UPrevPessoa in 'UPrevPessoa.pas' {fPrevPessoa},
  SelfPrintDefs in 'SelfPrintDefs.pas',
  SendMail in 'SendMail.pas',
  SendMailOptions in 'SendMailOptions.pas' {FormSendMailOptions},
  UPedidoRelAvulso in 'UPedidoRelAvulso.pas' {fPedidoRelAvulso},
  UPedidoRelPermanente in 'UPedidoRelPermanente.pas' {fPedidoRelPermanente},
  UPedidoRelPermanenteAprov in 'UPedidoRelPermanenteAprov.pas' {fPedidoRelPermanenteAprov},
  UConsCentroCusto in 'UConsCentroCusto.pas' {fConsCentroCusto},
  URelConsCCusto in 'URelConsCCusto.pas' {fRelConsCCusto},
  URelReciboCPagar in 'URelReciboCPagar.pas' {fRelReciboCPagar},
  URelRecibo in 'URelRecibo.pas' {fRelRecibo},
  URecibo in 'URecibo.pas' {fRecibo},
  URelReciboCob in 'URelReciboCob.pas' {fRelReciboCob},
  URelRecibo2 in 'URelRecibo2.pas' {fRelRecibo2},
  UPrevRecibo2 in 'UPrevRecibo2.pas' {fPrevRecibo2},
  URelRecibo3 in 'URelRecibo3.pas' {fRelRecibo3},
  uOrcServ in 'uOrcServ.pas' {fOrcServ},
  URelPessoas in 'URelPessoas.pas' {fRelPessoas},
  UPagtoComissao in 'UPagtoComissao.pas' {fPagtoComissao},
  uRelEnvelope1 in 'uRelEnvelope1.pas' {fRelEnvelope1},
  rsDBUtils in '..\rslib\nova\rsDBUtils.pas',
  uPessoaHist in 'uPessoaHist.pas' {fPessoaHist},
  uPessoaChaves in 'uPessoaChaves.pas' {fPessoaChaves},
  uVersaoC in 'uVersaoC.pas' {fVersaoC},
  uVersao in 'uVersao.pas' {fVersao},
  uDmVersao in 'uDmVersao.pas' {dmVersao: TDataModule},
  uDmRemoto in 'uDmRemoto.pas' {dmRemoto: TDataModule},
  uIntegracao in 'uIntegracao.pas',
  uUtilPadrao in 'uUtilPadrao.pas',
  uPessoa_Usuario in 'uPessoa_Usuario.pas' {fPessoa_Usuario},
  uPessoa_Sistema in 'uPessoa_Sistema.pas' {fPessoa_Sistema},
  USistema in 'USistema.pas' {fSistema};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'ServiSoft';
  Application.CreateForm(TfMenu, fMenu);
  Application.CreateForm(TDm1, Dm1);
  Application.CreateForm(TDmCons, DmCons);
  Application.Run;
end.
